### ISSUE TITLE
Declaration of Innoflash\SteroidSeeder\Factory::of($class) should be 

### ISSUE THREAD

**Issue by vishalinfyom** [innoflash/steroid-seeder#1]
Getting below error while seeding data using your seeder

```
Declaration of Innoflash\SteroidSeeder\Factory::of($class) should be compatible with Illuminate\Database\Eloquent\Factory::of($class, $name = 'default')

```

**Comment by innoflash** [comment]
Hi @vishalinfyom , can you please give me steps to reproduce the problem.

Also which version of Laravel is it?

**Comment by vishalinfyom** [comment]
@innoflash i'm using laravel `v6.18.23`

**Comment by innoflash** [comment]
Alright, i will look into it later

**Comment by innoflash** [comment]
0 => ***@***.***"
  1 => ***@***.***"
  2 => ***@***.***"
  3 => ***@***.***"
  4 => ***@***.***"
